# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 780))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.o_tw = QtWidgets.QTableWidget(self.tab_1)
        self.o_tw.setGeometry(QtCore.QRect(10, 10, 850, 730))
        self.o_tw.setObjectName("o_tw")
        self.o_tw.setColumnCount(0)
        self.o_tw.setRowCount(0)
        self.o_set_stat = QtWidgets.QComboBox(self.tab_1)
        self.o_set_stat.setGeometry(QtCore.QRect(870, 50, 100, 30))
        self.o_set_stat.setObjectName("o_set_stat")
        self.o_apply = QtWidgets.QPushButton(self.tab_1)
        self.o_apply.setGeometry(QtCore.QRect(870, 10, 100, 28))
        self.o_apply.setObjectName("o_apply")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.i_tw = QtWidgets.QTableWidget(self.tab_2)
        self.i_tw.setGeometry(QtCore.QRect(10, 40, 980, 700))
        self.i_tw.setObjectName("i_tw")
        self.i_tw.setColumnCount(0)
        self.i_tw.setRowCount(0)
        self.i_gender = QtWidgets.QComboBox(self.tab_2)
        self.i_gender.setGeometry(QtCore.QRect(600, 10, 140, 20))
        self.i_gender.setObjectName("i_gender")
        self.i_brand = QtWidgets.QComboBox(self.tab_2)
        self.i_brand.setGeometry(QtCore.QRect(750, 10, 140, 20))
        self.i_brand.setObjectName("i_brand")
        self.i_refresh = QtWidgets.QPushButton(self.tab_2)
        self.i_refresh.setGeometry(QtCore.QRect(900, 10, 90, 23))
        self.i_refresh.setObjectName("i_refresh")
        self.i_search = QtWidgets.QLineEdit(self.tab_2)
        self.i_search.setGeometry(QtCore.QRect(10, 10, 580, 20))
        self.i_search.setObjectName("i_search")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.u_tw = QtWidgets.QTableWidget(self.tab_3)
        self.u_tw.setGeometry(QtCore.QRect(10, 40, 980, 710))
        self.u_tw.setObjectName("u_tw")
        self.u_tw.setColumnCount(0)
        self.u_tw.setRowCount(0)
        self.u_search = QtWidgets.QLineEdit(self.tab_3)
        self.u_search.setGeometry(QtCore.QRect(10, 10, 580, 20))
        self.u_search.setObjectName("u_search")
        self.u_refresh = QtWidgets.QPushButton(self.tab_3)
        self.u_refresh.setGeometry(QtCore.QRect(900, 10, 90, 23))
        self.u_refresh.setObjectName("u_refresh")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.o_apply.setText(_translate("MainWindow", "apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "заказы"))
        self.i_refresh.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "товары"))
        self.u_refresh.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Пользователи"))
