# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 240))
        MainWindow.setMaximumSize(QtCore.QSize(400, 240))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_signin = QtWidgets.QPushButton(self.centralwidget)
        self.pb_signin.setGeometry(QtCore.QRect(110, 180, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_signin.sizePolicy().hasHeightForWidth())
        self.pb_signin.setSizePolicy(sizePolicy)
        self.pb_signin.setObjectName("pb_signin")
        self.le_password = QtWidgets.QLineEdit(self.centralwidget)
        self.le_password.setGeometry(QtCore.QRect(10, 60, 180, 20))
        self.le_password.setInputMask("")
        self.le_password.setFrame(True)
        self.le_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_password.setCursorPosition(0)
        self.le_password.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.le_password.setClearButtonEnabled(False)
        self.le_password.setObjectName("le_password")
        self.le_username = QtWidgets.QLineEdit(self.centralwidget)
        self.le_username.setGeometry(QtCore.QRect(10, 20, 180, 20))
        self.le_username.setObjectName("le_username")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 0, 180, 20))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 180, 20))
        self.label_2.setObjectName("label_2")
        self.le_name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_name.setGeometry(QtCore.QRect(200, 20, 180, 20))
        self.le_name.setObjectName("le_name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 0, 180, 20))
        self.label_4.setObjectName("label_4")
        self.le_surname = QtWidgets.QLineEdit(self.centralwidget)
        self.le_surname.setGeometry(QtCore.QRect(200, 60, 180, 20))
        self.le_surname.setObjectName("le_surname")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 40, 180, 20))
        self.label_5.setObjectName("label_5")
        self.le_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.le_phone.setGeometry(QtCore.QRect(200, 100, 180, 20))
        self.le_phone.setObjectName("le_phone")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 80, 180, 20))
        self.label_6.setObjectName("label_6")
        self.le_adress = QtWidgets.QLineEdit(self.centralwidget)
        self.le_adress.setGeometry(QtCore.QRect(200, 140, 180, 20))
        self.le_adress.setObjectName("le_adress")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 120, 180, 20))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 180, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создать нового пользователя"))
        self.pb_signin.setText(_translate("MainWindow", "создать новую учетную запись"))
        self.label_1.setText(_translate("MainWindow", "*имя пользователя:"))
        self.label_2.setText(_translate("MainWindow", "*пароль:"))
        self.label_4.setText(_translate("MainWindow", "имя:"))
        self.label_5.setText(_translate("MainWindow", "фамилия:"))
        self.label_6.setText(_translate("MainWindow", "телефон:"))
        self.label_7.setText(_translate("MainWindow", "адрес:"))
        self.label_3.setText(_translate("MainWindow", "* - обязательно"))
